version: "3.9"
x-app: &default-app
  build: '.'
  volumes:
    - .:/usr/src/app
    - /tmp/frizzl/mysqld:/var/run/mysqld

  depends_on:
    - db
  restart: "unless-stopped"

services:
  web:
    << : *default-app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    
  tailwind:
    <<: *default-app
    command: "python3 manage.py tailwind start"
    tty: true
    ports:
      - "8383:8383"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    volumes:
      - ./data/db:/var/lib/mysql/
      - /tmp/frizzl/mysqld:/var/run/mysqld
      
    environment:
      MYSQL_DATABASE: 'frizzl'
      MYSQL_USER: 'newuser'
      MYSQL_PASSWORD: 'user123'
      MYSQL_ROOT_PASSWORD: 'root123'


  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    restart: always
    ports:
      - 8080:80

    environment:
      - PMA_ARBITRARY=1

    depends_on: 
      - db

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@google.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #     - PGADMIN_LISTEN_PORT=5050

  #   volumes:
  #     - ./data/pgadmin:/var/lib/pgadmin/

  #   depends_on:
  #     - db

  #   ports:
  #     - "5050:5050"
